/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HMS.GUI;

import HMS.test.HMSdatabase_manager;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;


public class customerList extends javax.swing.JFrame {

    private HMSdatabase_manager database = null;
    public String cusSelected;
    private javax.swing.JTextField jtf_cusID;
    
    public customerList(HMSdatabase_manager database,javax.swing.JTextField jtf_cusID) {
        initComponents();
        initListener();
        this.setTheme();
        this.setLocationRelativeTo(null);
        
        this.database = database;
        this.jtf_cusID = jtf_cusID;
        setUpdateTable("");
    }
    //<editor-fold defaultstate="collapsed" desc="Coding by self">
    
    private void setTheme(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource(Constant.MINILOGO_HMS)));
    }
    public void setUpdateTable(String Cus_Keyword){
        DefaultTableModel model = new DefaultTableModel();
        model = database.QueryTable("SELECT cus_ID,cus_Name\n" +
                "FROM customer\n" +
                "WHERE cus_Name LIKE '%"+Cus_Keyword+"%';");
        jtb_customer.setModel(model);
    }
    private void initListener() {
        jbt_okay.addActionListener((ActionEvent) -> {
            setUpdateTable(jtf_cusName.getText());
        });
        
        jbt_select.addActionListener((ActionEvent) -> {
            int row = jtb_customer.getSelectedRow();
            cusSelected = (String) jtb_customer.getValueAt(row, 0);
            System.out.println("(printf from"+this.getClass().getName()+") you select : "+cusSelected);
            jtf_cusID.setText(cusSelected);
            this.setVisible(false);
        });
    }
    //</editor-fold>
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtf_cusName = new javax.swing.JTextField();
        jbt_okay = new javax.swing.JButton();
        jbt_select = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtb_customer = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("รายชื่อลูกค้า");
        setMinimumSize(new java.awt.Dimension(239, 344));
        setResizable(false);

        jLabel1.setText("ชื่อลูกค้า:");

        jbt_okay.setText("ตกลง");
        jbt_okay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jbt_select.setText("เลือก");
        jbt_select.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jtb_customer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtb_customer);
        if (jtb_customer.getColumnModel().getColumnCount() > 0) {
            jtb_customer.getColumnModel().getColumn(0).setResizable(false);
            jtb_customer.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtf_cusName, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbt_okay)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbt_select)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_okay)
                    .addComponent(jtf_cusName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jbt_select)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbt_okay;
    private javax.swing.JButton jbt_select;
    private javax.swing.JTable jtb_customer;
    private javax.swing.JTextField jtf_cusName;
    // End of variables declaration//GEN-END:variables
}
