/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HMS.GUI;

import HMS.test.HMSdatabase_manager;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class employeeList extends javax.swing.JFrame {
    private HMSdatabase_manager database = null;
    public String empSelected;
    private javax.swing.JTextField jtf_AddMaC_EmpId;
    
    public employeeList(HMSdatabase_manager database,javax.swing.JTextField jtf_cusID) {
        initComponents();
        initListener();
        this.setTheme();
        this.setLocationRelativeTo(null);
        
        this.database = database;
        this.jtf_AddMaC_EmpId = jtf_cusID;
        setUpdateTable("");
    }
    //<editor-fold defaultstate="collapsed" desc="Coding by self">
    private void setTheme(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource(Constant.MINILOGO_HMS)));
    }

    public void setUpdateTable(String Cus_Keyword){
        DefaultTableModel model = new DefaultTableModel();
        model = database.QueryTable("SELECT emp_ID, emp_Name\n" +
                "FROM employee\n" +
                "WHERE emp_Name LIKE '%"+Cus_Keyword+"%';");
        jtb_employee.setModel(model);
    }
    private void initListener() {
        jbt_okay.addActionListener((ActionEvent) -> {
            setUpdateTable(jtf_EmpName.getText());
        });
        
        jbt_select.addActionListener((ActionEvent) -> {
            int row = jtb_employee.getSelectedRow();
            empSelected = (String) jtb_employee.getValueAt(row, 0);
            System.out.println("(printf from"+this.getClass().getName()+") you select : " + empSelected);
            jtf_AddMaC_EmpId.setText(empSelected);
            this.setVisible(false);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtf_EmpName = new javax.swing.JTextField();
        jbt_okay = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_employee = new javax.swing.JTable();
        jbt_select = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("รายชื่อพนักงาน");
        setMinimumSize(new java.awt.Dimension(254, 350));
        setResizable(false);
        setSize(new java.awt.Dimension(254, 335));

        jLabel1.setText("ชื่อพนักงงาน:");

        jbt_okay.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jbt_okay.setText("ตกลง");
        jbt_okay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jtb_employee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtb_employee);

        jbt_select.setText("เลือก");
        jbt_select.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtf_EmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbt_okay))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbt_select)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtf_EmpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_okay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt_select)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbt_okay;
    private javax.swing.JButton jbt_select;
    private javax.swing.JTable jtb_employee;
    private javax.swing.JTextField jtf_EmpName;
    // End of variables declaration//GEN-END:variables
}
