/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HMS.GUI;

import HMS.test.HMSdatabase_manager;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;

public class herbList extends javax.swing.JFrame {
    private HMSdatabase_manager database = null;
    public String herbSelected;
    private javax.swing.JTextField jtf_AddOrder_herbName;
    public herbList(HMSdatabase_manager database,javax.swing.JTextField jtf_AddOrder_herbName) {
        initComponents();
        initListener();
        this.setTheme();
        this.setLocationRelativeTo(null);
        
        this.database = database;
        this.jtf_AddOrder_herbName = jtf_AddOrder_herbName;
        setUpdateTable("");
    }
    //<editor-fold defaultstate="collapsed" desc="Coding by self">
    private void setTheme(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource(Constant.MINILOGO_HMS)));
    }

    public void setUpdateTable(String Herb_Keyword){
        DefaultTableModel model = new DefaultTableModel();
        model = database.QueryTable("SELECT herb_ID,herb_name\n" +
                "FROM herb\n" +
                "WHERE herb_name LIKE '%"+Herb_Keyword+"%';");
        jtb_herb.setModel(model);
    }
    private void initListener() {
        jbt_okay.addActionListener((ActionEvent) -> {
            setUpdateTable(jtf_herbName.getText());
        });
        
        jbt_select.addActionListener((ActionEvent) -> {
            int row = jtb_herb.getSelectedRow();
            herbSelected = (String) jtb_herb.getValueAt(row, 0);
            System.out.println("(printf from"+this.getClass().getName()+") you select : "+herbSelected);
            jtf_AddOrder_herbName.setText(herbSelected);
            this.setVisible(false);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtf_herbName = new javax.swing.JTextField();
        jbt_okay = new javax.swing.JButton();
        jbt_select = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtb_herb = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("รายชื่อสมุนไพร");

        jbt_okay.setText("ตกลง");
        jbt_okay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jbt_select.setText("เลือก");
        jbt_select.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jtb_herb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtb_herb);
        if (jtb_herb.getColumnModel().getColumnCount() > 0) {
            jtb_herb.getColumnModel().getColumn(0).setResizable(false);
            jtb_herb.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel1.setText("ชื่อสมุนไพร:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_herbName, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbt_select)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_okay))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_okay)
                    .addComponent(jtf_herbName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jbt_select)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbt_okay;
    private javax.swing.JButton jbt_select;
    private javax.swing.JTable jtb_herb;
    private javax.swing.JTextField jtf_herbName;
    // End of variables declaration//GEN-END:variables
}
